# Generated by Django 5.2 on 2025-05-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
